---
title: "Data viz"
author: "Christopher Rohde"
date: "17/6/2021"
output: html_document
---
#ctrl+alt+I for at lave nedenstående code punkter. ctrl + shift + m hvis du vil lave %>% 
```{r}
#load packages
source(here::here("R/package-loading.R"))

# load the tidied dataset
load(here::here("data/nhanes_small.rda"))
```

# One variable plots
```{r continuous-variables}
ggplot(nhanes_small, aes(x = bmi)) + 
    geom_density()

ggplot(nhanes_small, aes(x = bmi)) +
    geom_histogram()
```

```{r discrete-variables}
ggplot(nhanes_small, aes(x = sex)) +
    geom_bar()

ggplot(nhanes_small, aes(x = diabetes)) +
    geom_bar()
```

```{r remove-missing-diabetes}
nhanes_tidied <- nhanes_small %>% 
    filter(!is.na(diabetes))

usethis::use_data(nhanes_tidied, overwrite = T)

ggplot(nhanes_tidied, aes(x = diabetes)) + 
    geom_bar()
```

# Plotting two variables
```{r 2-continuous-variables}
bmi_chol <- ggplot(nhanes_tidied, aes(x = bmi, y = tot_chol)) 

bmi_chol + 
    geom_point()

bmi_chol +
    geom_hex()

bmi_chol +
    geom_smooth()

bmi_chol + 
    geom_hex() +
    geom_smooth()
```

```{r 2-discrete variables}
two_discrete <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex)) 

two_discrete + 
    geom_bar()

two_discrete + 
    geom_bar(position = position_dodge())
```

```{r discrete-continuous-variables}
two_mixed <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, y = bmi))

two_mixed +
    geom_boxplot()

two_mixed + 
    geom_jitter()

two_mixed +
    geom_violin()

```





# Plotting three or more variables
```{r using-colour}
# 1 continuous and 2 discrete variables
nhanes_tidied %>% 
    ggplot(aes(x = sex, y = bp_sys_ave, colour = diabetes)) + 
    geom_boxplot()

# 3 continous variables
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point()

# 2 continious and 1 discrete variable
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = diabetes)) + 
    geom_point()
```

```{r using-faceting}
# side by side
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) + 
    geom_point() +
    facet_grid(cols = vars(diabetes))

#stacked
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) + 
    geom_point() +
    facet_grid(rows = vars(diabetes))

# 5 variables
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) + 
    geom_point() +
    facet_grid(rows = vars(diabetes), cols = vars(sex))

```

